title: PantherX Operating System
description: PantherX OS is a modern, secure, privacy-first operating system with a efficient desktop environment and thousands of applications.
baseurl: ""
url: ""
destination: _site

contact:
  - title: team@pantherx.org
    url: mailto:team@pantherx.org?subject=Team Enquiry
    caption: Discuss ideas, ask questions, join us!
  - title: support@pantherx.org
    url: mailto:support@pantherx.org?subject=Support Enquiry
    caption: Get help with PantherX
  - title: pantherx.social
    url: https://pantherx.social/
    caption: Join us on the new Twitter - Mastodon
  - title: chat.pantherx.org
    url: https://matrix.to/#/#public:pantherx.org
    caption: Chat with us on Matrix
  - title: pantherx.dev
    url: https://www.pantherx.dev/
    caption: Hire us

# Build settings
markdown: kramdown

nav:
  platform:
    - title: Panther Alpha (ext.)
      permalink: http://www.panther-mpc.com/panther-alpha/
    - title: PantherX OS
      permalink: /#PantherX+Operating+System
    - title: PantherX for Business
      permalink: /panther-for-business/

include:
  - .well-known
  - .well-known/matrix/client
  - .well-known/matrix/server

exclude:
  - src/
  - gulpfile.js
  - package.json
  - package-lock.json
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
  - .bit.json
  - .bitmap
  - yarn-error.log
  - bit.json
  - s3_website.yml
  - project.config
  - run.sh

collections:
  pages:
    output: true
  features:
    output: true
  sections:
    output: false
  topics:
    output: true
  news:
    output: true
  applications:
    output: true

defaults:
  - scope:
      path: "_news" # an empty string here means all files in the project
    values:
      cover:
        height: medium
        image: bg_01.jpg
  - scope:
      path: "assets/images/panther-for-business"
    values:
      image: true
  - scope:
      path: "_applications"
    values:
      cover:
        height: medium
        image: bg_122.jpg

author:
  - title: Franz Geffke
    picture: franz.svg
    about: ...
    ref: franz
